# Generated by Django 5.2.9 on 2026-01-05 02:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefone")),
                (
                    "phone_normalized",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=20,
                        verbose_name="Telefone Normalizado",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        help_text="CPF do cliente (usado para acompanhamento)",
                        max_length=14,
                        verbose_name="CPF",
                    ),
                ),
                (
                    "cpf_normalized",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=11,
                        verbose_name="CPF Normalizado",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notas visíveis apenas para vendedores",
                        verbose_name="Observações internas",
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False,
                        help_text="Impede novos pedidos",
                        verbose_name="Bloqueado",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Total"
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("confirmed", "Confirmado"),
                            ("completed", "Concluído"),
                            ("cancelled", "Cancelado"),
                            ("returned", "Devolvido"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status do Pedido",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("paid", "Pago"),
                            ("refunded", "Reembolsado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status do Pagamento",
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("shipped", "Enviado"),
                            ("delivered", "Entregue"),
                            ("ready_for_pickup", "Pronto para retirada"),
                            ("picked_up", "Retirado"),
                            ("failed_attempt", "Tentativa de entrega"),
                            ("expired", "Expirado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status da Entrega",
                    ),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Retirada na Loja"),
                            ("motoboy", "Motoboy"),
                            ("sedex", "SEDEX"),
                            ("pac", "PAC"),
                        ],
                        default="motoboy",
                        max_length=20,
                        verbose_name="Tipo de Entrega",
                    ),
                ),
                (
                    "delivery_address",
                    models.TextField(blank=True, verbose_name="Endereço de Entrega"),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Código de Rastreio"
                    ),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enviado em"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Entregue em"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Para retiradas não realizadas",
                        null=True,
                        verbose_name="Expira em",
                    ),
                ),
                (
                    "cancel_reason",
                    models.TextField(blank=True, verbose_name="Motivo do cancelamento"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cancelado em"
                    ),
                ),
                (
                    "return_reason",
                    models.TextField(blank=True, verbose_name="Motivo da devolução"),
                ),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Devolvido em"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        help_text="Visível apenas para vendedores",
                        verbose_name="Notas internas",
                    ),
                ),
                (
                    "is_priority",
                    models.BooleanField(default=False, verbose_name="Prioritário"),
                ),
                (
                    "delivery_attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Tentativas de entrega"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="orders.customer",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vendedor",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("created", "Pedido criado"),
                            ("status_changed", "Status alterado"),
                            ("payment_received", "Pagamento recebido"),
                            ("shipped", "Enviado"),
                            ("delivered", "Entregue"),
                            ("ready_pickup", "Pronto para retirada"),
                            ("picked_up", "Retirado"),
                            ("failed_attempt", "Tentativa de entrega"),
                            ("cancelled", "Cancelado"),
                            ("returned", "Devolvido"),
                            ("refunded", "Reembolsado"),
                            ("delivery_type_changed", "Tipo de entrega alterado"),
                            ("note_added", "Nota adicionada"),
                            ("notification_sent", "Notificação enviada"),
                            ("expired", "Expirado"),
                            ("edited", "Editado"),
                        ],
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadados"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="orders.order",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atividade",
                "verbose_name_plural": "Atividades",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "phone_normalized"],
                name="orders_cust_tenant__316036_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "cpf_normalized"],
                name="orders_cust_tenant__d03376_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("tenant", "phone_normalized"),
                name="unique_customer_phone_per_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["tenant", "created_at"], name="orders_orde_tenant__8eff50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["tenant", "order_status"], name="orders_orde_tenant__503d01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["tenant", "delivery_type"],
                name="orders_orde_tenant__05dcfb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["tenant", "delivery_status"],
                name="orders_orde_tenant__666c2f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["code"], name="orders_orde_code_77e86c_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["tracking_code"], name="orders_orde_trackin_252782_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["expires_at"], name="orders_orde_expires_f5acda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderactivity",
            index=models.Index(
                fields=["order", "created_at"], name="orders_orde_order_i_aad6f1_idx"
            ),
        ),
    ]
