# Generated by Django 5.2.9 on 2026-01-04 02:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefone")),
                (
                    "phone_normalized",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=20,
                        verbose_name="Telefone Normalizado",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Total"
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("confirmed", "Confirmado"),
                            ("completed", "Concluído"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status do Pedido",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("pending", "Pendente"), ("paid", "Pago")],
                        default="pending",
                        max_length=20,
                        verbose_name="Status do Pagamento",
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("shipped", "Enviado"),
                            ("delivered", "Entregue"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status da Entrega",
                    ),
                ),
                (
                    "delivery_address",
                    models.TextField(blank=True, verbose_name="Endereço de Entrega"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="orders.customer",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vendedor",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "phone_normalized"],
                name="orders_cust_tenant__316036_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("tenant", "phone_normalized"),
                name="unique_customer_phone_per_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["tenant", "created_at"], name="orders_orde_tenant__8eff50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["tenant", "order_status"], name="orders_orde_tenant__503d01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["code"], name="orders_orde_code_77e86c_idx"),
        ),
    ]
