# Generated by Django 5.2.9 on 2026-01-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[("delivery", "Entrega"), ("pickup", "Retirada na loja")],
                default="delivery",
                max_length=20,
                verbose_name="Tipo de entrega",
            ),
        ),
    ]
