# Generated by Django 5.2.9 on 2026-01-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_delivery_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("shipped", "Enviado"),
                    ("delivered", "Entregue"),
                    ("ready_for_pickup", "Pronto para retirada"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status da Entrega",
            ),
        ),
    ]
