# Generated by Django 5.2.9 on 2026-01-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_sale_date"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="order",
            new_name="orders_orde_tenant__9ec487_idx",
            old_name="orders_orde_tenant__sale_idx",
        ),
    ]
