# Generated by Django 5.2.9 on 2026-01-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_add_tracking_and_timestamps"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="order",
            new_name="orders_orde_tenant__05dcfb_idx",
            old_name="orders_orde_tenant__delivery_idx",
        ),
        migrations.RenameIndex(
            model_name="order",
            new_name="orders_orde_trackin_252782_idx",
            old_name="orders_orde_trackin_idx",
        ),
    ]
