# Generated by Django 5.2.9 on 2026-01-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_motoboy_fields"),
        (
            "orders",
            "0005_rename_orders_orde_tenant__sale_idx_orders_orde_tenant__9ec487_idx",
        ),
    ]

    operations = []
