# Generated by Django 5.2.9 on 2026-01-04 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_add_cpf_to_customer"),
        (
            "orders",
            "0005_rename_orders_orde_tenant__delivery_idx_orders_orde_tenant__05dcfb_idx_and_more",
        ),
    ]

    operations = []
