# Generated by Django 5.2.9 on 2026-01-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_rename_indices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("pickup", "Retirada na Loja"),
                    ("motoboy", "Motoboy"),
                    ("sedex", "SEDEX"),
                    ("pac", "PAC"),
                    ("mandae", "Mandaê"),
                ],
                default="motoboy",
                max_length=20,
                verbose_name="Tipo de Entrega",
            ),
        ),
    ]
