# Generated by Django 5.2.9 on 2026-01-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_merge_20260109_1434"),
        ("orders", "0006_order_motoboy_fields"),
    ]

    operations = []
