# Generated by Django 5.2.9 on 2026-01-08 00:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="apirequestlog",
            new_name="integration_correla_1d7208_idx",
            old_name="integration_correla_j0k1l2_idx",
        ),
        migrations.RenameIndex(
            model_name="apirequestlog",
            new_name="integration_instanc_9e29d6_idx",
            old_name="integration_instanc_m3n4o5_idx",
        ),
        migrations.RenameIndex(
            model_name="apirequestlog",
            new_name="integration_status__d182f4_idx",
            old_name="integration_status__p6q7r8_idx",
        ),
        migrations.RenameIndex(
            model_name="apirequestlog",
            new_name="integration_endpoin_d85f69_idx",
            old_name="integration_endpoin_s9t0u1_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationlog",
            new_name="integration_tenant__a86faa_idx",
            old_name="integration_tenant__6d3a8e_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationlog",
            new_name="integration_order_i_07e654_idx",
            old_name="integration_order_i_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationlog",
            new_name="integration_status_8a9480_idx",
            old_name="integration_status__d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationlog",
            new_name="integration_notific_25f25d_idx",
            old_name="integration_notific_g7h8i9_idx",
        ),
    ]
