# Generated by Django 5.2.9 on 2026-01-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "integrations",
            "0002_rename_integration_correla_j0k1l2_idx_integration_correla_1d7208_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="apirequestlog",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="error_code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
    ]
