# Generated by Django 5.2.9 on 2026-01-04 02:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="E-mail de contato"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "whatsapp_enabled",
                    models.BooleanField(default=True, verbose_name="WhatsApp Ativo"),
                ),
                (
                    "msg_order_created",
                    models.TextField(
                        default="Olá {nome}!\n\nSeu pedido *{codigo}* foi recebido.\nValor: R$ {valor}\n\nObrigado pela preferência!",
                        help_text="Placeholders disponíveis: {nome}, {codigo}, {valor}",
                        verbose_name="Mensagem: Pedido Criado",
                    ),
                ),
                (
                    "msg_order_shipped",
                    models.TextField(
                        default="Olá {nome}!\n\nSeu pedido *{codigo}* foi enviado.\n\nEm breve chegará no endereço informado.",
                        help_text="Placeholders disponíveis: {nome}, {codigo}",
                        verbose_name="Mensagem: Pedido Enviado",
                    ),
                ),
                (
                    "msg_order_delivered",
                    models.TextField(
                        default="Olá {nome}!\n\nSeu pedido *{codigo}* foi entregue.\n\nObrigado por comprar conosco!",
                        help_text="Placeholders disponíveis: {nome}, {codigo}",
                        verbose_name="Mensagem: Pedido Entregue",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração",
                "verbose_name_plural": "Configurações",
                "ordering": ["tenant"],
            },
        ),
    ]
