# Generated by Django 5.2.9 on 2026-01-05 02:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="E-mail de contato"),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone de contato"
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Endereço para retiradas",
                        verbose_name="Endereço",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "whatsapp_enabled",
                    models.BooleanField(default=False, verbose_name="WhatsApp Ativo"),
                ),
                (
                    "evolution_api_url",
                    models.URLField(
                        blank=True,
                        help_text="Ex: https://api.evolution.com.br",
                        verbose_name="URL da Evolution API",
                    ),
                ),
                (
                    "evolution_api_key",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="API Key da Evolution"
                    ),
                ),
                (
                    "evolution_instance",
                    models.CharField(
                        blank=True,
                        help_text="Nome da instância criada na Evolution API",
                        max_length=100,
                        verbose_name="Nome da Instância",
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="Número conectado (apenas visualização)",
                        max_length=20,
                        verbose_name="Número do WhatsApp",
                    ),
                ),
                (
                    "whatsapp_connected",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="WhatsApp Conectado"
                    ),
                ),
                (
                    "msg_order_created",
                    models.TextField(
                        default="Olá {nome}! 🎉\n\nSeu pedido *{codigo}* foi recebido!\nValor: R$ {valor}\n\nAcompanhe seu pedido em:\n{link_rastreio}\n\nObrigado pela preferência!\n_{loja}_",
                        help_text="Placeholders: {nome}, {codigo}, {valor}, {loja}",
                        verbose_name="Mensagem: Pedido Criado",
                    ),
                ),
                (
                    "msg_order_confirmed",
                    models.TextField(
                        default="Olá {nome}! ✅\n\nSeu pedido *{codigo}* foi confirmado e está sendo preparado!\n\n_{loja}_",
                        help_text="Placeholders: {nome}, {codigo}, {loja}",
                        verbose_name="Mensagem: Pedido Confirmado",
                    ),
                ),
                (
                    "msg_payment_received",
                    models.TextField(
                        default="Olá {nome}! 💰\n\nRecebemos o pagamento do seu pedido *{codigo}*!\nValor: R$ {valor}\n\nObrigado!\n_{loja}_",
                        help_text="Placeholders: {nome}, {codigo}, {valor}, {loja}",
                        verbose_name="Mensagem: Pagamento Recebido",
                    ),
                ),
                (
                    "msg_payment_refunded",
                    models.TextField(
                        default="Olá {nome}!\n\nO valor de R$ {valor} referente ao pedido *{codigo}* foi estornado.\n\nEm caso de dúvidas, entre em contato.\n_{loja}_",
                        help_text="Placeholders: {nome}, {codigo}, {valor}, {loja}",
                        verbose_name="Mensagem: Pagamento Estornado",
                    ),
                ),
                (
                    "msg_order_shipped",
                    models.TextField(
                        default="Olá {nome}! 📦\n\nSeu pedido *{codigo}* foi enviado!\n\n{rastreio_info}Acompanhe em:\n{link_rastreio}\n\n_{loja}_",
                        help_text="Placeholders: {nome}, {codigo}, {rastreio}, {link_rastreio}, {loja}",
                        verbose_name="Mensagem: Pedido Enviado",
                    ),
                ),
                (
                    "msg_order_delivered",
                    models.TextField(
                        default="Olá {nome}! ✅\n\nSeu pedido *{codigo}* foi entregue!\n\nObrigado por comprar conosco! 😊\n_{loja}_",
                        help_text="Placeholders: {nome}, {codigo}, {loja}",
                        verbose_name="Mensagem: Pedido Entregue",
                    ),
                ),
                (
                    "msg_delivery_failed",
                    models.TextField(
                        default="Olá {nome}! ⚠️\n\nTentamos entregar seu pedido *{codigo}* mas não conseguimos.\nTentativa: {tentativa}\n\nPor favor, verifique o endereço ou entre em contato.\n_{loja}_",
                        help_text="Placeholders: {nome}, {codigo}, {tentativa}, {loja}",
                        verbose_name="Mensagem: Tentativa de Entrega Falha",
                    ),
                ),
                (
                    "msg_order_ready_for_pickup",
                    models.TextField(
                        default="Olá {nome}! 🏬\n\nSeu pedido *{codigo}* está pronto para retirada!\nValor: R$ {valor}\n\n📍 Retire em:\n{endereco}\n\n⏰ Prazo: 48 horas\n\nAguardamos você!\n_{loja}_",
                        help_text="Placeholders: {nome}, {codigo}, {valor}, {endereco}, {loja}",
                        verbose_name="Mensagem: Pronto para Retirada",
                    ),
                ),
                (
                    "msg_order_picked_up",
                    models.TextField(
                        default="Olá {nome}! ✅\n\nSeu pedido *{codigo}* foi retirado com sucesso!\n\nObrigado pela preferência! 😊\n_{loja}_",
                        help_text="Placeholders: {nome}, {codigo}, {loja}",
                        verbose_name="Mensagem: Pedido Retirado",
                    ),
                ),
                (
                    "msg_order_expired",
                    models.TextField(
                        default="Olá {nome}! ⚠️\n\nInfelizmente o prazo para retirada do pedido *{codigo}* expirou.\n\nEntre em contato para verificar as opções disponíveis.\n_{loja}_",
                        help_text="Placeholders: {nome}, {codigo}, {loja}",
                        verbose_name="Mensagem: Pedido Expirado (Retirada)",
                    ),
                ),
                (
                    "msg_order_cancelled",
                    models.TextField(
                        default="Olá {nome}!\n\nSeu pedido *{codigo}* foi cancelado.\n{motivo_info}\nEm caso de dúvidas, entre em contato.\n_{loja}_",
                        help_text="Placeholders: {nome}, {codigo}, {motivo}, {loja}",
                        verbose_name="Mensagem: Pedido Cancelado",
                    ),
                ),
                (
                    "msg_order_returned",
                    models.TextField(
                        default="Olá {nome}!\n\nRegistramos a devolução do pedido *{codigo}*.\n{motivo_info}\nObrigado pelo contato.\n_{loja}_",
                        help_text="Placeholders: {nome}, {codigo}, {motivo}, {loja}",
                        verbose_name="Mensagem: Pedido Devolvido",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração",
                "verbose_name_plural": "Configurações",
                "ordering": ["tenant"],
            },
        ),
    ]
