# Generated by Django 5.2.9 on 2026-01-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_remove_global_api_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantsettings",
            name="msg_order_ready_for_pickup",
            field=models.TextField(
                default="Olá {nome}! 🏬\n\nSeu pedido *{codigo}* está pronto para retirada!\nValor: R$ {valor}\n\n🔑 *Código de retirada: {pickup_code}*\n\n📍 Retire em:\n{endereco}\n\n⏰ Prazo: 48 horas\n\nApresente o código na loja.\n_{loja}_",
                help_text="Placeholders: {nome}, {codigo}, {valor}, {endereco}, {pickup_code}, {loja}",
                verbose_name="Mensagem: Pronto para Retirada",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                help_text="Número conectado (preenchido automaticamente)",
                max_length=20,
                verbose_name="Número do WhatsApp",
            ),
        ),
    ]
