# Generated by Django 5.2.9 on 2026-01-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_add_pickup_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantsettings",
            name="msg_order_created",
            field=models.TextField(
                default="Olá {nome}! 🎉\n\nSeu pedido *{codigo}* foi recebido!\nValor: R$ {valor}\n\nObrigado pela preferência!",
                help_text="Placeholders disponíveis: {nome}, {codigo}, {valor}",
                verbose_name="Mensagem: Pedido Criado",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="msg_order_delivered",
            field=models.TextField(
                default="Olá {nome}! ✅\n\nSeu pedido *{codigo}* foi entregue!\n\nObrigado por comprar conosco!",
                help_text="Placeholders disponíveis: {nome}, {codigo}",
                verbose_name="Mensagem: Pedido Entregue",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="msg_order_shipped",
            field=models.TextField(
                default="Olá {nome}! 📦\n\nSeu pedido *{codigo}* foi enviado!\n",
                help_text="Placeholders disponíveis: {nome}, {codigo}. Rastreio é adicionado automaticamente.",
                verbose_name="Mensagem: Pedido Enviado",
            ),
        ),
    ]
