# Generated by Django 5.2.9 on 2026-01-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_granular_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantsettings",
            name="msg_delivery_failed",
            field=models.TextField(
                blank=True,
                default="Olá {nome}! ⚠️\n\nTentamos entregar seu pedido *{codigo}* mas não conseguimos.\nTentativa: {tentativa}\n\nPor favor, verifique o endereço ou entre em contato.\n_{loja}_",
                help_text="Placeholders: {nome}, {codigo}, {tentativa}, {loja}",
                verbose_name="Mensagem: Tentativa de Entrega Falha",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="msg_order_cancelled",
            field=models.TextField(
                blank=True,
                default="Olá {nome}!\n\nSeu pedido *{codigo}* foi cancelado.\n{motivo_info}Em caso de dúvidas, entre em contato.\n_{loja}_",
                help_text="Placeholders: {nome}, {codigo}, {motivo}, {motivo_info}, {loja}",
                verbose_name="Mensagem: Pedido Cancelado",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="msg_order_confirmed",
            field=models.TextField(
                blank=True,
                default="Olá {nome}! ✅\n\nSeu pedido *{codigo}* foi confirmado e está sendo preparado!\n\n_{loja}_",
                help_text="Placeholders: {nome}, {codigo}, {loja}",
                verbose_name="Mensagem: Pedido Confirmado",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="msg_order_created",
            field=models.TextField(
                blank=True,
                default="Olá {nome}! 🎉\n\nSeu pedido *{codigo}* foi recebido!\nValor: R$ {valor}\n\nAcompanhe seu pedido em:\n{link_rastreio}\n\nObrigado pela preferência!\n_{loja}_",
                help_text="Placeholders: {nome}, {codigo}, {valor}, {loja}, {link_rastreio}",
                verbose_name="Mensagem: Pedido Criado",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="msg_order_delivered",
            field=models.TextField(
                blank=True,
                default="Olá {nome}! ✅\n\nSeu pedido *{codigo}* foi entregue!\n\nObrigado por comprar conosco! 😊\n_{loja}_",
                help_text="Placeholders: {nome}, {codigo}, {loja}",
                verbose_name="Mensagem: Pedido Entregue",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="msg_order_expired",
            field=models.TextField(
                blank=True,
                default="Olá {nome}! ⚠️\n\nInfelizmente o prazo para retirada do pedido *{codigo}* expirou.\n\nEntre em contato para verificar as opções disponíveis.\n_{loja}_",
                help_text="Placeholders: {nome}, {codigo}, {loja}",
                verbose_name="Mensagem: Pedido Expirado (Retirada)",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="msg_order_picked_up",
            field=models.TextField(
                blank=True,
                default="Olá {nome}! ✅\n\nSeu pedido *{codigo}* foi retirado com sucesso!\n\nObrigado pela preferência! 😊\n_{loja}_",
                help_text="Placeholders: {nome}, {codigo}, {loja}",
                verbose_name="Mensagem: Pedido Retirado",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="msg_order_ready_for_pickup",
            field=models.TextField(
                blank=True,
                default="Olá {nome}! 🏬\n\nSeu pedido *{codigo}* está pronto para retirada!\nValor: R$ {valor}\n\n🔑 *Código de retirada: {pickup_code}*\n\n📍 Retire em:\n{endereco}\n\n⏰ Prazo: 48 horas\n\nApresente o código na loja.\n_{loja}_",
                help_text="Placeholders: {nome}, {codigo}, {valor}, {endereco}, {pickup_code}, {loja}",
                verbose_name="Mensagem: Pronto para Retirada",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="msg_order_returned",
            field=models.TextField(
                blank=True,
                default="Olá {nome}!\n\nRegistramos a devolução do pedido *{codigo}*.\n{motivo_info}Obrigado pelo contato.\n_{loja}_",
                help_text="Placeholders: {nome}, {codigo}, {motivo}, {motivo_info}, {loja}",
                verbose_name="Mensagem: Pedido Devolvido",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="msg_order_shipped",
            field=models.TextField(
                blank=True,
                default="Olá {nome}! 📦\n\nSeu pedido *{codigo}* foi enviado!\n\n{rastreio_info}Acompanhe em:\n{link_rastreio}\n\n_{loja}_",
                help_text="Placeholders: {nome}, {codigo}, {rastreio}, {rastreio_info}, {link_rastreio}, {loja}",
                verbose_name="Mensagem: Pedido Enviado",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="msg_payment_received",
            field=models.TextField(
                blank=True,
                default="Olá {nome}! 💰\n\nRecebemos o pagamento do seu pedido *{codigo}*!\nValor: R$ {valor}\n\nObrigado!\n_{loja}_",
                help_text="Placeholders: {nome}, {codigo}, {valor}, {loja}",
                verbose_name="Mensagem: Pagamento Recebido",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="msg_payment_refunded",
            field=models.TextField(
                blank=True,
                default="Olá {nome}!\n\nO valor de R$ {valor} referente ao pedido *{codigo}* foi estornado.\n\nEm caso de dúvidas, entre em contato.\n_{loja}_",
                help_text="Placeholders: {nome}, {codigo}, {valor}, {loja}",
                verbose_name="Mensagem: Pagamento Estornado",
            ),
        ),
    ]
