# Generated by Django 5.2.9 on 2026-01-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_payment_failed_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantsettings",
            name="msg_payment_failed",
            field=models.TextField(
                blank=True,
                default="Olá {nome}! ⚠️\n\nO pagamento do pedido *{codigo}* não foi aprovado.\n\nPor favor, tente novamente ou entre em contato.\n\n_{loja}_",
                help_text="Placeholders: {nome}, {codigo}, {valor}, {loja}",
                verbose_name="Mensagem: Pagamento Falhou",
            ),
        ),
    ]
