# Generated by Django 5.2.9 on 2026-01-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0009_alter_tenantsettings_msg_payment_failed"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="correios_cartao_postagem",
            field=models.CharField(
                blank=True,
                help_text="Número do cartão de postagem (opcional)",
                max_length=20,
                verbose_name="Cartão de Postagem",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="correios_contrato",
            field=models.CharField(
                blank=True,
                help_text="Número do contrato com os Correios (opcional)",
                max_length=20,
                verbose_name="Código do Contrato",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="correios_enabled",
            field=models.BooleanField(default=False, verbose_name="Correios Ativo"),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="correios_senha",
            field=models.CharField(
                blank=True,
                help_text="Senha ou Token da API",
                max_length=100,
                verbose_name="Senha/Token Correios",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="correios_usuario",
            field=models.CharField(
                blank=True,
                help_text="Usuário da API dos Correios (Meu Correios)",
                max_length=50,
                verbose_name="Usuário Correios",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="mandae_api_url",
            field=models.URLField(
                blank=True,
                default="https://api.mandae.com.br/v2/",
                verbose_name="URL da API Mandaê",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="mandae_customer_id",
            field=models.CharField(
                blank=True,
                help_text="ID do cliente na Mandaê",
                max_length=100,
                verbose_name="Customer ID Mandaê",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="mandae_enabled",
            field=models.BooleanField(default=False, verbose_name="Mandaê Ativo"),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="mandae_token",
            field=models.CharField(
                blank=True,
                help_text="Token de autenticação da API",
                max_length=100,
                verbose_name="Token Mandaê",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="mandae_tracking_prefix",
            field=models.CharField(
                blank=True,
                help_text="Ex: ATSNR",
                max_length=10,
                verbose_name="Prefixo de Rastreio",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="mandae_webhook_secret",
            field=models.CharField(
                blank=True,
                help_text="Chave para validar webhooks recebidos",
                max_length=100,
                verbose_name="Webhook Secret",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="motoboy_max_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Deixe vazio para não ter limite",
                max_digits=8,
                null=True,
                verbose_name="Valor Máximo Motoboy",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="motoboy_min_price",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text="Valor mínimo cobrado",
                max_digits=8,
                verbose_name="Valor Mínimo Motoboy",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="motoboy_price_per_km",
            field=models.DecimalField(
                decimal_places=2,
                default=2.5,
                help_text="Valor cobrado por quilômetro",
                max_digits=6,
                verbose_name="Preço por Km (Motoboy)",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="store_cep",
            field=models.CharField(
                blank=True,
                help_text="CEP de origem para cálculos de frete",
                max_length=9,
                verbose_name="CEP da Loja",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="store_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Preenchido automaticamente a partir do CEP",
                max_digits=9,
                null=True,
                verbose_name="Latitude da Loja",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="store_lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Preenchido automaticamente a partir do CEP",
                max_digits=9,
                null=True,
                verbose_name="Longitude da Loja",
            ),
        ),
    ]
