# Generated by Django 5.2.9 on 2026-01-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0010_logistics_integration_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenantsettings",
            name="correios_senha",
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="correios_codigo_acesso",
            field=models.CharField(
                blank=True,
                help_text="Código de acesso gerado no portal Meu Correios",
                max_length=100,
                verbose_name="Código de Acesso",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="correios_token",
            field=models.TextField(
                blank=True, editable=False, verbose_name="Token (automático)"
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="correios_token_expira",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Expiração do Token"
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="correios_cartao_postagem",
            field=models.CharField(
                blank=True,
                help_text="Opcional: para APIs que exigem cartão",
                max_length=20,
                verbose_name="Cartão de Postagem",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="correios_contrato",
            field=models.CharField(
                blank=True,
                help_text="Opcional: para APIs que exigem contrato",
                max_length=20,
                verbose_name="Número do Contrato",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="correios_usuario",
            field=models.CharField(
                blank=True,
                help_text="Seu usuário do portal Meu Correios",
                max_length=50,
                verbose_name="Usuário (Meu Correios)",
            ),
        ),
    ]
