# Generated by Django 5.2.9 on 2026-01-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0011_correios_token_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="motoboy_max_radius",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Distância máxima atendida. Deixe vazio para sem limite.",
                max_digits=6,
                null=True,
                verbose_name="Raio Máximo (km)",
            ),
        ),
    ]
