# Generated by Django 5.2.9 on 2026-01-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="paymentlink",
            new_name="payments_pa_tenant__888fee_idx",
            old_name="payments_pa_tenant__7f5c8e_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentlink",
            new_name="payments_pa_pagarme_8e579f_idx",
            old_name="payments_pa_pagarme_8e2f3a_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentlink",
            new_name="payments_pa_pagarme_9340ea_idx",
            old_name="payments_pa_pagarme_c1d9e2_idx",
        ),
        migrations.AlterField(
            model_name="paymentlink",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="paymentlink",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
