# Generated by Django 5.2.9 on 2026-01-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_paymentlink_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentlink",
            name="order",
        ),
        migrations.AddField(
            model_name="paymentlink",
            name="pagarme_checkout_id",
            field=models.CharField(
                blank=True, null=True, db_index=True, max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="paymentlink",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Aguardando"),
                    ("paid", "Pago"),
                    ("failed", "Falhou"),
                    ("expired", "Expirado"),
                    ("canceled", "Cancelado"),
                    ("refunded", "Estornado"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
