# Generated by Django 5.2.9 on 2026-01-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_paymentlink_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentlink",
            name="payer_address_city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
        ),
        migrations.AddField(
            model_name="paymentlink",
            name="payer_address_complement",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Complemento"
            ),
        ),
        migrations.AddField(
            model_name="paymentlink",
            name="payer_address_neighborhood",
            field=models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
        ),
        migrations.AddField(
            model_name="paymentlink",
            name="payer_address_number",
            field=models.CharField(blank=True, max_length=20, verbose_name="Número"),
        ),
        migrations.AddField(
            model_name="paymentlink",
            name="payer_address_state",
            field=models.CharField(blank=True, max_length=2, verbose_name="UF"),
        ),
        migrations.AddField(
            model_name="paymentlink",
            name="payer_address_street",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Rua do Pagador"
            ),
        ),
        migrations.AddField(
            model_name="paymentlink",
            name="payer_address_zip",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="CEP do Pagador"
            ),
        ),
        migrations.AddField(
            model_name="paymentlink",
            name="payer_document",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="CPF/CNPJ do Pagador"
            ),
        ),
        migrations.AddField(
            model_name="paymentlink",
            name="payer_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="E-mail do Pagador"
            ),
        ),
        migrations.AddField(
            model_name="paymentlink",
            name="payer_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nome do Pagador"
            ),
        ),
        migrations.AddField(
            model_name="paymentlink",
            name="payer_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Telefone do Pagador"
            ),
        ),
    ]
