# Generated by Django 5.2.9 on 2026-01-24 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_paymentlink_payer_address_city_and_more"),
        ("tenants", "0012_motoboy_max_radius"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentlink",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant"
            ),
        ),
    ]
